version: '3.8'

services:
  blog:
    build: ./application
    container_name: blog-app-v1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_TITLE=My Blog
      - APP_PORT=3000

  bot:
    build: ./bot
    container_name: xss-bot-v1
    restart: always
    ports:
      - "3001:3001"
    environment:
      - BOT_PORT=3001
      - CTF_FLAG=ev{x55_v1_d0m_b453d_5t0r3d}
      - APP_URL=http://blog:3000
    depends_on:
      - blog
